[project]
name = "lending-platform"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.p2p-lending]
path = "contracts/p2p-lending.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
